/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTextArea;

/**
 *
 * @author Anthony
 */
public class ViewPrescription extends javax.swing.JFrame {

    /**
     * Creates new form Prescription
     */
    public ViewPrescription() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPatientTitle = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        txtPatient = new javax.swing.JTextArea();
        jScrollPane16 = new javax.swing.JScrollPane();
        txtDosage = new javax.swing.JTextArea();
        lblDoctorTitle = new javax.swing.JLabel();
        lblNotesTitle = new javax.swing.JLabel();
        jScrollPane18 = new javax.swing.JScrollPane();
        txtDoctor = new javax.swing.JTextArea();
        lblDosageTitle = new javax.swing.JLabel();
        jScrollPane19 = new javax.swing.JScrollPane();
        txtNotes = new javax.swing.JTextArea();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Prescription | PAA");

        lblPatientTitle.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblPatientTitle.setText("Patient");

        jScrollPane11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txtPatient.setEditable(false);
        txtPatient.setBackground(java.awt.SystemColor.control);
        txtPatient.setColumns(20);
        txtPatient.setFont(new java.awt.Font("Monospaced", 0, 17)); // NOI18N
        txtPatient.setLineWrap(true);
        txtPatient.setRows(5);
        jScrollPane11.setViewportView(txtPatient);

        txtDosage.setEditable(false);
        txtDosage.setBackground(java.awt.SystemColor.control);
        txtDosage.setColumns(20);
        txtDosage.setFont(new java.awt.Font("Monospaced", 0, 17)); // NOI18N
        txtDosage.setLineWrap(true);
        txtDosage.setRows(5);
        jScrollPane16.setViewportView(txtDosage);

        lblDoctorTitle.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblDoctorTitle.setText("Doctor");

        lblNotesTitle.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblNotesTitle.setText("Notes");

        jScrollPane18.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txtDoctor.setEditable(false);
        txtDoctor.setBackground(java.awt.SystemColor.control);
        txtDoctor.setColumns(20);
        txtDoctor.setFont(new java.awt.Font("Monospaced", 0, 17)); // NOI18N
        txtDoctor.setLineWrap(true);
        txtDoctor.setRows(5);
        jScrollPane18.setViewportView(txtDoctor);

        lblDosageTitle.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblDosageTitle.setText("Dosage");

        txtNotes.setEditable(false);
        txtNotes.setBackground(java.awt.SystemColor.control);
        txtNotes.setColumns(20);
        txtNotes.setFont(new java.awt.Font("Monospaced", 0, 17)); // NOI18N
        txtNotes.setLineWrap(true);
        txtNotes.setRows(5);
        jScrollPane19.setViewportView(txtNotes);

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnBack.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDosageTitle)
                            .addComponent(lblNotesTitle)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(lblPatientTitle)
                                            .addGap(345, 345, 345)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblDoctorTitle)
                                        .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(btnBack)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientTitle)
                    .addComponent(lblDoctorTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblNotesTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDosageTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnBack() {
        return btnBack;
    }

    public JTextArea getTxtDoctor() {
        return txtDoctor;
    }

    public JTextArea getTxtDosage() {
        return txtDosage;
    }

    public JTextArea getTxtNotes() {
        return txtNotes;
    }

    public JTextArea getTxtPatient() {
        return txtPatient;
    }

    public void addBackEventHandler(ActionListener listener) {
        btnBack.addActionListener(listener);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JLabel lblDoctorTitle;
    private javax.swing.JLabel lblDosageTitle;
    private javax.swing.JLabel lblNotesTitle;
    private javax.swing.JLabel lblPatientTitle;
    private javax.swing.JTextArea txtDoctor;
    private javax.swing.JTextArea txtDosage;
    private javax.swing.JTextArea txtNotes;
    private javax.swing.JTextArea txtPatient;
    // End of variables declaration//GEN-END:variables
}
