/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JTextArea;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Anthony
 */
public class AdminView extends javax.swing.JFrame {

    /**
     * Creates new form AdminView
     */
    public AdminView() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        lstDoctors = new javax.swing.JList<>();
        lblDoctors = new javax.swing.JLabel();
        btnAddAccount = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnDeleteDoctor = new javax.swing.JButton();
        lblSecretaries = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstSecretaries = new javax.swing.JList<>();
        btnDeleteSecretary = new javax.swing.JButton();
        jScrollPane20 = new javax.swing.JScrollPane();
        txtFeedbackMessage = new javax.swing.JTextArea();
        lblFeedbackTitle = new javax.swing.JLabel();
        btnProvideFeedback = new javax.swing.JButton();
        lblPatientCommentsTitle = new javax.swing.JLabel();
        jScrollPane21 = new javax.swing.JScrollPane();
        lstComments = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblWelcome.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblWelcome.setText("Welcome");

        lstDoctors.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lstDoctors.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstDoctors.setToolTipText("");
        scrollPane.setViewportView(lstDoctors);

        lblDoctors.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblDoctors.setText("Doctors");

        btnAddAccount.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnAddAccount.setText("Add Account");

        btnLogout.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnLogout.setText("Log Out");

        btnDeleteDoctor.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnDeleteDoctor.setText("Delete Doctor Account");

        lblSecretaries.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblSecretaries.setText("Secretaries");

        lstSecretaries.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lstSecretaries.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(lstSecretaries);

        btnDeleteSecretary.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnDeleteSecretary.setText("Delete Secretary Account");

        txtFeedbackMessage.setColumns(20);
        txtFeedbackMessage.setFont(new java.awt.Font("Monospaced", 0, 17)); // NOI18N
        txtFeedbackMessage.setLineWrap(true);
        txtFeedbackMessage.setRows(5);
        jScrollPane20.setViewportView(txtFeedbackMessage);

        lblFeedbackTitle.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblFeedbackTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFeedbackTitle.setText("Feedback Message");

        btnProvideFeedback.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnProvideFeedback.setText("Provide Feedback");

        lblPatientCommentsTitle.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblPatientCommentsTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPatientCommentsTitle.setText("Patient Comments");

        lstComments.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lstComments.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane21.setViewportView(lstComments);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddAccount)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(lblSecretaries)
                                    .addComponent(btnDeleteSecretary, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblDoctors)
                                    .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(btnDeleteDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane20)
                                    .addComponent(btnProvideFeedback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane21, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
                                    .addComponent(lblFeedbackTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPatientCommentsTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblWelcome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLogout)))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogout)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDoctors, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSecretaries))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblFeedbackTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnProvideFeedback)
                        .addGap(36, 36, 36)
                        .addComponent(lblPatientCommentsTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane21)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteDoctor)
                    .addComponent(btnDeleteSecretary))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddAccount)
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnAddAccount() {
        return btnAddAccount;
    }

    public JLabel getLblWelcome() {
        return lblWelcome;
    }

    public JButton getBtnDeleteDoctor() {
        return btnDeleteDoctor;
    }

    public JButton getBtnDeleteSecretary() {
        return btnDeleteSecretary;
    }

    public JButton getBtnLogout() {
        return btnLogout;
    }

    public JButton getBtnProvideFeedback() {
        return btnProvideFeedback;
    }

    public JList<String> getLstComments() {
        return lstComments;
    }

    public JList<String> getLstDoctors() {
        return lstDoctors;
    }

    public JList<String> getLstSecretaries() {
        return lstSecretaries;
    }

    public JTextArea getTxtFeedbackMessage() {
        return txtFeedbackMessage;
    }
    
    public void addLogoutEventHandler(ActionListener listener) {
        btnLogout.addActionListener(listener);
    }
    
    public void addAddAccountEventHandler(ActionListener listener) {
        btnAddAccount.addActionListener(listener);
    }
    
    public void addDeleteDoctorEventHandler(ActionListener listener) {
        btnDeleteDoctor.addActionListener(listener);
    }
    
    public void addDeleteSecretaryEventHandler(ActionListener listener) {
        btnDeleteSecretary.addActionListener(listener);
    }
    
    public void addProvideFeedbackEventHandler(ActionListener listener) {
        btnProvideFeedback.addActionListener(listener);
    }
    
    public void addDoctorsChangedListener(ListSelectionListener listener) {
        lstDoctors.addListSelectionListener(listener);
    }
    
    public void addSecretariesChangedListener(ListSelectionListener listener) {
        lstSecretaries.addListSelectionListener(listener);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAccount;
    private javax.swing.JButton btnDeleteDoctor;
    private javax.swing.JButton btnDeleteSecretary;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnProvideFeedback;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblDoctors;
    private javax.swing.JLabel lblFeedbackTitle;
    private javax.swing.JLabel lblPatientCommentsTitle;
    private javax.swing.JLabel lblSecretaries;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JList<String> lstComments;
    private javax.swing.JList<String> lstDoctors;
    private javax.swing.JList<String> lstSecretaries;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTextArea txtFeedbackMessage;
    // End of variables declaration//GEN-END:variables
}
