/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.awt.event.FocusListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Anthony
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        lblErrorInvalidLogin = new javax.swing.JLabel();
        btnRequestAccount = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login | PAA");

        lblTitle.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 48)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtUsername.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        txtUsername.setForeground(java.awt.Color.gray);
        txtUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsername.setText("Username");
        txtUsername.setToolTipText("");
        txtUsername.setPreferredSize(new java.awt.Dimension(544, 36));

        txtPassword.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        txtPassword.setForeground(java.awt.Color.gray);
        txtPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPassword.setText("Password");
        txtPassword.setPreferredSize(new java.awt.Dimension(544, 36));

        btnLogin.setFont(new java.awt.Font("Yu Gothic Medium", 0, 24)); // NOI18N
        btnLogin.setText("Login");

        lblErrorInvalidLogin.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        lblErrorInvalidLogin.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorInvalidLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblErrorInvalidLogin.setText("Invalid credentials, please try again");

        btnRequestAccount.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        btnRequestAccount.setText("Request New Account");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblErrorInvalidLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRequestAccount)))
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle)
                .addGap(45, 45, 45)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(lblErrorInvalidLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(btnRequestAccount)
                .addContainerGap())
        );

        lblErrorInvalidLogin.setVisible(false);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * standard accessor for ui elements
     *
     * @return - returns login button
     */
    public JButton getBtnLogin() {
        return btnLogin;
    }

    /**
     * standard accessor for ui elements
     *
     * @return - returns the password box
     */
    public JPasswordField getTxtPassword() {
        return txtPassword;
    }

    /**
     * standard accessor
     * @return - returns error label for a username that wasnt found
     */
    public JLabel getLblErrorInvalidLogin() {
        return lblErrorInvalidLogin;
    }

    /**
     * standard accessor for ui elements
     *
     * @return - returns the username box
     */
    public JTextField getTxtUsername() {
        return txtUsername;
    }

    public JButton getbtnRequestAccount() {
        return btnRequestAccount;
    }

    /**
     * adds event handler to login button and password field (so can press
     * enter)
     *
     * @param listener - login listener to add
     */
    public void addLoginEventHandler(ActionListener listener) {
        btnLogin.addActionListener(listener);
        txtPassword.addActionListener(listener);
    }
    
    public void addRequestEventHandler(ActionListener listener) {
        btnRequestAccount.addActionListener(listener);
    }
    public void addUsernamePlaceholder(FocusListener listener) {
        txtUsername.addFocusListener(listener);
    }
    
    public void addPasswordPlaceholder(FocusListener listener) {
        txtPassword.addFocusListener(listener);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRequestAccount;
    private javax.swing.JLabel lblErrorInvalidLogin;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
